name: jobs work flow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - run: echo"${{ github.job }}"

  job_2:
    runs-on: windows-latest
    needs: job_1
    steps:
    - run: echo"${{ github.job }} "

  job_3:
    runs-on: macos-13
    needs: job_1
    steps:
    - run: echo"${{ github.job }}"

  job_4:
    runs-on: macos-latest
    needs: job_1
    steps:
    - run: echo"${{ github.job }}"

  
